WIP - Cloud 8 to 9 upgrade testing hackery
Add a new std-upgrade model to the available set of vagrant models,
which is tailored to support Cloud8 to Cloud9 upgrade testing, which
leverages the above cloud version specific input model construction
mechanism.

Add tooling to implement Cloud update testing, e.g. updating to latest
Updates packages, or testing Updates-test packages against a cloud with
Pool+Updates, or testing update from Devel to Staging.

Add tooling to implement Cloud upgrade testing, e.g. upgrading from
Cloud8 to Cloud9 for devel, staging, updates or updates-test.

Add support to run-upgrade to allow services in the base Cloud8
deployment to be disabled.

Change-Id: Ib4e3972747da5cdb30843c38fde94afc76256371

diff --git a/bin/run-update b/bin/run-update
--- a/bin/run-update
+++ b/bin/run-update
@@ -14,8 +14,8 @@
 # License for the specific language governing permissions and limitations
 # under the License.
 #
-# Run through the Ardana upgrade workflow to update the Cloud
-# from Cloud8 to Cloud9, for selected Devel or Product stream.
+# Run through the Ardana update workflow to update the Cloud
+# within the same stream using updated package sources.
 #
 
 set -eux
@@ -23,8 +23,6 @@ set -o pipefail
 
 cmd_name="$(basename ${BASH_SOURCE[0]})"
 cmd_dir="$(dirname "$(readlink -e "${BASH_SOURCE[0]}")")"
-adt_top="$(dirname "${cmd_dir}")"
-log_file="${adt_top}/logs/${cmd_name}.log"
 
 eval "$(${cmd_dir}/ardana-env)"
 
@@ -34,36 +32,43 @@ usage() {
     echo
     echo "cloud defaults to deployerincloud"
     echo
-    echo "--hos               -- Use the HOS flavour of Cloud8; SOC is default."
-    echo "--c8-run-tests      -- Tempest test the C8 cloud before upgrade."
-    echo "--devel             -- Test DC8 ==> DC9 upgrade. (default)"
-    echo "--disable           -- Specify service-component to disable. (repeatable)"
-    echo "--staging           -- Test DC8S ==> DC9S upgrade."
-    echo "--updates           -- Test C8+Updates ==> C9+Updates upgrade."
-    echo "--updates-test      -- Test C8+Updates-test ==> C9+Updates-test upgrade."
+    echo "--c8, --c8-devel    -- Test DC8 ==> DC8S update."
+    echo "--c8-hos            -- Use the HOS flavour of Cloud8; SOC is default."
+    echo "--c8-pool           -- Test C8 Pool ==> Updates update."
+    echo "--c8-updates        -- Test C8 Pool + Updates ==> Updates-test update."
+    echo "--c9, --c9-devel    -- Test DC9 ==> DC9S update. (default)"
+    echo "--c9-pool           -- Test C9 Pool ==> Updates update."
+    echo "--c9-updates        -- Test C9 Pool + Updates ==> Updates-test update."
     echo "--no-setup          -- Don't run dev-env-install.yml."
     echo "--no-update-rpms    -- Don't build RPMs from local clones."
+    echo "--patch             -- Use the zypper patch method."
     echo "--pre-destroy       -- Destroy any existing instance of cloud first."
     echo "--rhel-compute      -- Enable RHEL computes."
     echo "--sles-compute      -- Enable SLES computes (default)."
+    echo "--update            -- Use the zypper update method."
 }
 
 # Manage list of long options as a sorted array of option names which
 # we then join with commas to form the argument to getopt
 long_opts=(
+    c8
+    c8-devel
+    c8-hos
+    c8-pool
+    c8-updates
+    c9
+    c9-devel
+    c9-pool
+    c9-updates
     ci
-    c8-run-tests
-    hos
-    devel
-    disable
-    updates
-    updates-test
     help
     no-setup
     no-update-rpms
+    patch
     pre-destroy
     rhel-compute
     sles-compute
+    update
 )
 
 # join long_opts members with ","
@@ -80,12 +85,12 @@ fi
 # Note the quotes around `$TEMP': they are essential!
 eval set -- "$TEMP"
 
+cloud_version=
 pre_destroy=
-zypper_method=dist-upgrade
-common_args=( --no-ansible-sync )
-cloud_type=
-cloud8_args=( --c8 )
-cloud9_args=( --c9 )
+zypper_method=
+common_args=()
+cloud_args=()
+update_args=()
 
 
 while true ; do
@@ -94,26 +99,42 @@ while true ; do
         usage
         exit 0
         ;;
-    (--disable)
-        cloud8_args+=( "--disable-services" "${2}" )
-        shift 2
-        ;;
-    (--c8-run-tests)
-        cloud8_args+=( "--run-tests" )
-        shift
-        ;;
-    (--hos)
-        cloud8_args+=( "--c8-hos" )
-        shift
-        ;;
-    (--devel|--staging|--updates|--updates-test)
-        cloud_type="${1:2}"
+    (--c8|--c8-*|--c9|--c9-*)
+        cloud_version="${1:3:1}"
+        case "${1}" in
+        (*-devel)
+            cloud_args+=( "--c${cloud_version}-devel" )
+            update_args+=( "--c${cloud_version}-staging" )
+            ;;
+        (*-hos)
+            if [[ "${cloud_version}" != "8" ]]
+            then
+                echo "ERROR: There is no HOS variant for Cloud${cloud_version}!"
+                exit 1
+            fi
+            common_args+=( "${1}" )
+            ;&
+        (*-pool)
+            cloud_args+=( "--c${cloud_version}-pool" )
+            update_args+=( "--c${cloud_version}-updates" )
+            ;;
+        (*-updates)
+            cloud_args+=( "--c${cloud_version}-updates" )
+            update_args+=( "--c${cloud_version}-updates-test" )
+            ;;
+        esac
         shift
         ;;
     (--rhel-compute|--sles-compute)
-        ;&
+        common_args+=( "${1}" )
+        shift
+        ;;
     (--ci|--no-setup|--no-update-rpms)
         common_args+=( "${1}" )
+        shift
+        ;;
+    (--patch|--update)
+        zypper_method="${1:2}"
         shift
         ;;
     (--pre-destroy)
@@ -130,30 +151,35 @@ while true ; do
     esac
 done
 
-# default to Devel cloud sources if none specified
-if [[ -z "${cloud_type:-}" ]]
+if [[ -z "${cloud_version}" ]]
 then
-    cloud_type=devel
+    cloud_version=9
 fi
 
-# Set the desired cloudsource for both clouds
-cloud8_args+=( "--c8-${cloud_type}" )
-cloud9_args+=( "--c9-${cloud_type}" )
+if [[ -z "${zypper_method}" ]]
+then
+    zypper_method=update
+fi
 
-# Check if running under a tty and set options appropriately
+# Ensure common args has something in it to keep bash checking happy
+common_args+=( --c${cloud_version} )
+
+if (( ${#cloud_args[@]} == 0 ))
+then
+    cloud_args+=( "--c${cloud_version}-devel" )
+fi
+
+if (( ${#update_args[@]} == 0 ))
+then
+    update_args+=( "--c${cloud_version}-staging" )
+fi
+
 if [[ -t 1 ]]
 then
     ssh_opts="-t"
-    export ANSIBLE_FORCE_COLOR=True
-    export VAGRANT_FORCE_COLOR=True
 else
     ssh_opts=
 fi
-
-# log stdout & stderr to file as well as terminal
-# NOTE: may need to use less -R to read log content if running against a terminal
-exec > >(tee "${log_file}")
-exec 2>&1
 
 deployer_ssh()
 {
@@ -220,67 +246,63 @@ ardana_scratch_update_status()
 
 deployer_needs_update()
 {
-    ardana_scratch_update_status deployer 2>&1 | grep "ardana-update.yml"
+    ardana_scratch_update_status "${1}" 2>&1 | grep "ardana-update.yml"
 }
 
 deployer_needs_reboot()
 {
-    ardana_scratch_update_status deployer 2>&1 | grep "ardana-reboot.yml"
+    ardana_scratch_update_status "${1}" 2>&1 | grep "ardana-reboot.yml"
 }
+
+
 
 set -x
 
 cloud_name="${1:-adt}"
-vagrant_dir="${adt_top}/ardana-vagrant-models/${cloud_name}-vagrant"
-ansible_dir="${adt_top}/ansible"
+vagrant_dir="${cmd_dir}/../ardana-vagrant-models/${cloud_name}-vagrant"
+ansible_dir="${cmd_dir}/../ansible"
 
-# Retrieve artifacts needed for both Cloud8 and Cloud9 runs
+# Retrieve artifacts for initial cloud and updates runs
 ${cmd_dir}/astack.sh \
     "${common_args[@]}" \
-    "${cloud8_args[@]}" \
+    "${cloud_args[@]}" \
     ${pre_destroy} \
+    --no-update-rpms \
     --no-cloud \
     "${cloud_name}"
-
-find "${adt_top}/../C8_NEW_RPMS" -type f -name "*.rpm"
 
 # no need to run setup phase again, so skip in future astack invocations
 common_args+=( --no-setup )
 
 ${cmd_dir}/astack.sh \
     "${common_args[@]}" \
-    "${cloud9_args[@]}" \
+    "${update_args[@]}" \
+    --no-update-rpms \
     --no-cloud \
     "${cloud_name}"
-
-find "${adt_top}/../C9_NEW_RPMS" -type f -name "*.rpm"
 
 # all artifacts have been retrieved so no need to retrieve again
 common_args+=( --no-artifacts )
 
-# all version specific override RPMs have been built at this point
-# so no need to build again.
-common_args+=( --no-update-rpms )
-
 # Force re-creation of the local input-model cache
 rm -rf "${vagrant_dir}/input-model"
 
-# Bring up the cloud, using already fetched artifacts, optionally
-# running tempest tests to confirm correct operation.
+# Bring up the cloud, using already fetched artifacts, running
+# tempest tests to confirm correct operation.
 ${cmd_dir}/astack.sh \
     "${common_args[@]}" \
-    "${cloud8_args[@]}" \
+    "${cloud_args[@]}" \
+    --run-tests \
     "${cloud_name}"
 
 source ${cmd_dir}/libci.sh
 
 pushd "${ansible_dir}"
 
-# disable/remove existing zypper repos on the deployer
+# disable/remove existing zypper repos
 ${cmd_dir}/ardana --cloud ${cloud_name} \
     ansible-playbook \
         -i hosts/cloud.yml \
-        --limit deployer \
         ${ansible_dir}/cloud-repos-update.yml \
         -e zypper_repo_enabled=no \
         -e zypper_repo_state=absent
@@ -288,7 +310,8 @@ ${cmd_dir}/ardana --cloud ${cloud_name} \
 # Switch to update cloud settings
 ${cmd_dir}/astack.sh \
     "${common_args[@]}" \
-    "${cloud9_args[@]}" \
+    "${update_args[@]}" \
+    --no-update-rpms \
     --no-cloud \
     "${cloud_name}"
 
@@ -296,32 +319,7 @@ ${cmd_dir}/astack.sh \
 ${cmd_dir}/ardana --cloud ${cloud_name} \
     ansible-playbook \
         -i hosts/cloud.yml \
-        cloud-deployer-repos.yml
-
-# dist-upgrade deployer from SLE 12 SP3 to SLE 12 SP4
-deployer_ssh sudo zypper dup -ly
-
-#FMCC## Now we need to reboot the deployer to finish the SLE 12 SP4
-#FMCC## dist-upgrade, but we want to do so in an Ardana service friendly
-#FMCC## fashion, so try to use the ardana-reboot playbook, though
-#FMCC## this will fail saying deployer node needs to be manually rebooted
-#FMCC## and that we need to run _ardana-post-reboot.yml after rebooting.
-#FMCC#ardana_scratch_run_playbook \
-#FMCC#    OPS-LM--first-member \
-#FMCC#    ardana-reboot || true
-
-#FMCC## Now "manually" reboot the deployer node
-#FMCC#${cmd_dir}/ardana --cloud ${cloud_name} \
-#FMCC#    ansible-playbook \
-#FMCC#        -i hosts/cloud.yml \
-#FMCC#        ${ansible_dir}/cloud-deployer-reboot.yml
-
-#FMCC## now run the _ardana_post-reboot.yml playbook
-#FMCC## TODO(fergal): May not want/need this as it would
-#FMCC## restart Cloud8 version of services...
-#FMCC#ardana_scratch_run_playbook \
-#FMCC#    OPS-LM--first-member \
-#FMCC#    _ardana-post-reboot
+        cloud-repos-update.yml
 
 # Install/Update Cloud pattern packages and run ardana-init, but skip model init
 ${cmd_dir}/ardana --cloud ${cloud_name} \
@@ -329,13 +327,6 @@ ${cmd_dir}/ardana --cloud ${cloud_name} \
         -i hosts/cloud.yml \
         cloud-deployer-init.yml \
         -e skip_model_init
-
-# TODO(fergal): Deal with any Cloud9 deprecation issues in the input model
-# copy the update-non-deployer-nodes script to the deployer
-deployer_scp cloud9-input-model-upgrade ${cmd_dir}/deployer/cloud9-input-model-upgrade
-
-# use update-non-deployer-nodes to update the remaining nodes in the cloud
-deployer_ssh ./cloud9-input-model-upgrade
 
 # config-cloud.sh should already be there but no harm in copying up again
 deployer_scp config-cloud.sh ${cmd_dir}/deployer/config-cloud.sh
@@ -346,26 +337,26 @@ deployer_ssh ./config-cloud.sh
 
 # run the update-pkgs playbook
 ardana_scratch_run_playbook \
-    OPS-LM--first-member:tempest_all \
+    OPS-LM--first-member \
     ardana-update-pkgs \
     -e zypper_update_method=${zypper_method} \
     -e zypper_update_gpg_checks=true \
     -e zypper_update_licenses_agree=true \
     -e zypper_update_include_reboot_patches=true
 
-#if deployer_needs_update
-#then
+if deployer_needs_update
+then
     ardana_scratch_run_playbook \
         OPS-LM--first-member \
         ardana-update
-#fi
+fi
 
-#if deployer_needs_reboot
-#then
+if deployer_needs_reboot
+then
     # this will fail saying deployer node needs to be manually rebooted
     # and that we need to run _ardana-post-reboot.yml after rebooting.
     ardana_scratch_run_playbook \
-        OPS-LM--first-member:tempest_all \
+        OPS-LM--first-member \
         ardana-reboot || true
 
     # Now "manually" reboot the deployer node
@@ -376,21 +367,15 @@ ardana_scratch_run_playbook \
 
     # now run the _ardana_post-reboot.yml playbook
     ardana_scratch_run_playbook \
-        OPS-LM--first-member:tempest_all \
+        OPS-LM--first-member \
         _ardana-post-reboot
-#fi
-
-# remove the C8-Overrides repo from other nodes
-deployer_ssh "cd scratch/ansible/next/ardana/ansible && ansible -b 'resources:!OPS-LM--first-member' -m shell -a 'zypper rr C8-Overrides' || true"
+fi
 
 # copy the update-non-deployer-nodes script to the deployer
 deployer_scp update-non-deployer-nodes ${cmd_dir}/deployer/update-non-deployer-nodes
 
 # use update-non-deployer-nodes to update the remaining nodes in the cloud
-deployer_ssh ./update-non-deployer-nodes ${zypper_method}
-
-# copy the run-tests.sh script to the deployer
-deployer_scp run-tests.sh ${cmd_dir}/deployer/run-tests.sh
+deployer_ssh ./update-non-deployer-nodes update
 
 # use run-tests.sh to validate cloud is working correctly
 deployer_ssh ./run-tests.sh ci ${cloud_name}
